### ISSUE TITLE
Pixel.js build script breaks pixel_wrapper

### ISSUE THREAD

**Issue by EricHanLiu** [DDMAL/pixel_wrapper#28]
The `index.html` file that's copied when running the `pixel.sh` script (notably the 
```
scp ./index.html ../../../../
``` 
line) is built specifically for the standalone Pixel.js, and doesn't work with the wrapper. It has the hardcoded manuscript loaded, and with the latest version now linked to the `pixel_wrapper` repo, there are more changes (namely `src` links) that aren't compatible with `pixel_wrapper`.

A possible solution is to have the user `git checkout` the `index.html` file after building everything with `pixel.sh`. I think this needs to be done since `Pixel.js` is now a submodule, so we can't change the `index.html` that they're copying, and that's built to work with the latest `diva.js`.

It's kind of a hacky fix, but since we can't really change the `Pixel.js` source code, it'll have to be something specific to the `pixel_wrapper` installation. I can add it to the python script, just have it comment out that one line that copies the `index.html` file.

**Comment by EricHanLiu** [comment]
Also needed to change the gulp command from just `gulp` to `gulp develop:rodan` so that the build doesn't hang at the end. This is all done in the python script `activate_wrapper.py`, which is run before the `pixel.sh` build script (order is detailed in README)

**Comment by EricHanLiu** [comment]
Added code to the python script so the user doesn't have to do any extra commands, just running the `activate_wrapper.py` will edit the `pixel.sh` script accordingly.

**Comment by EricHanLiu** [comment]
Just tested with fresh copy and building everything works properly now, the `pixel_wrapper` `index.html` is no longer touched, and the correct `gulp` command is run so the build no longer hangs.

**Comment by vigliensoni** [comment]
<o.o>/

**Comment by EricHanLiu** [comment]
<o.o>
