### ISSUE TITLE
Link the wrapper to the actual diva and pixel repos

### ISSUE THREAD

**Issue by zeyadhazem** [DDMAL/pixel_wrapper#4]
Use git submodules instead of having an old version of pixel and diva in this repo

**Comment by EricHanLiu** [comment]
Pixel repo is a submodule.

Not sure how to link the wrapper to Diva, since the wrapper itself seems to be a modified version of Diva

**Comment by EricHanLiu** [comment]
Closing since having Diva6 as a submodule seems unlikely when this repo is basically Diva6 with some added files and modifications
