### ISSUE TITLE
Need to change output port filetype to rgba 

### ISSUE THREAD

**Issue by EricHanLiu** [DDMAL/pixel_wrapper#6]
In order to match the CM job's input port filetypes

**Comment by martha-thomae** [comment]
Fixed this issue, waiting for [pull request](https://github.com/DDMAL/pixel_wrapper/pull/7) to be answered.

**Comment by EricHanLiu** [comment]
Needed to change input port filetype requirements as well, since despite them being optional ports they can still be created, and in that case there is no automatic conversion from rgb to rgba so need to keep consistency of rgba throughout.
Already fixed this issue and just need the pull request to be accepted.

**Comment by EricHanLiu** [comment]
Pull request accepted, closing.
